FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD AccountService.jar /opt/AccountService/
EXPOSE 8080
WORKDIR /opt/AccountService/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "AccountService.jar"]
